info:
  name: Create Role
  type: http
  seq: 1

http:
  method: POST
  url: "{{baseUrl}}/roles"
  headers:
    - name: Authorization
      value: Bearer {{accessToken}}
  body:
    type: json
    data: |-
      {
        "name": "STUDENT",
        "description": "Student role"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
